[package]
name = "bokeh"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24", optional = true }
num = "0.4"
paste = "1.0"
rayon = "1.6"

[features]
image = ["dep:image"]

[profile.dev]
opt-level = 3
